### PR TITLE
Corrected link to newsletter

### PR DESCRIPTION
**Pull request by holgergp**
Just corrected the link to the newsletter registration with the link you provided via twitter.

See https://github.com/quickstrom/quickstrom.io/pull/1

### CODE REVIEW

**Comment by holgergp** [comment]
The failing docker login does not seem to be related to this PR. 🤷‍♂️

**Comment by owickstrom** [comment]
Awesome, thank you! I'll have to fix the GitHub Action to not do docker stuff on PRs.

**Comment by holgergp** [comment]
👍
Yet it still feels weird that docker login works on main/master and not within a PR. Why should TTY be present on the former and not on the latter? 🤔 
For now I guess one does not need to publish the docker image from a PR. 
But still, should this be investigated further?

**Comment by owickstrom** [comment]
I added a conditional so it only does login and push on the `main` branch. Secrets aren't available in PR builds so it can't really work there, anyway.

**Pull request merged**
