### PR TITLE
Add additional browser options configurability.

### PR DESCRIPTION
**Pull request by jleonard-r7**
Unfortunately the integration test has some "derivation problem" I'm not familiar with how to debug. I was hoping you could take a look @owickstrom  ?

### CODE REVIEW

**Comment by jleonard-r7** [comment]
I think this is ready to merge now. The integration tests are passing in GH Actions.

**Comment by jleonard-r7** [comment]
Actually sorry. I've realized that we need to remove the `--incognito` flag if using `--user-data-dir`. I'll add that as a configuration option as well (to this PR). I think the other default arguments should all make sense for every use case.

**Comment by jleonard-r7** [comment]
I'm having trouble getting this to work. Seems like a chromedriver / chromium issue:

```
23:19 $ docker run --rm --network quickstrom -v "$PWD:/web-cljs" -v "$HOME/Desktop/WebDriver:/chrome-data"  jleonardr7/quickstrom quickstrom check --log-level=DEBUG --webdriver-host=webdriver --webdriver-path=/wd/hub --browser=chrome --browser-options="disable-web-security user-data-dir=/chrome-data profile-directory=profile1"  --tests=5 /web-cljs/quickstrom/specs/tcell.spec.purs /web-cljs/resources/public/index.html                              
   ____       _      _        _                               
  /___ \_   _(_) ___| | _____| |_ _ __ ___  _ __ ___         
 //  / / | | | |/ __| |/ / __| __| '__/ _ \| '_ ` _ \       
/ \_/ /| |_| | | (__|   <\__ \ |_| | | (_) | | | | | |     
\___,_\ \__,_|_|\___|_|\_\___/\__|_|  \___/|_| |_| |_|

Running 5 tests...

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

20 Actions
2020-12-04 07:19:43 DEBUG  Request Request POST http://webdriver:4444/wd/hub/session
{
    "capabilities": {
        "alwaysMatch": {
            "goog:chromeOptions": {
                "args": [
                    "headless",
                    "disable-gpu",
                    "disable-web-security",
                    "profile-directory=profile1",
                    "user-data-dir=/chrome-data"
                ],
                "binary": "/usr/bin/google-chrome"
            },
            "browserName": "chrome"
        }
    },
    "desiredCapabilities": {}
}
2020-12-04 07:19:43 ERROR  HTTP Exception HttpExceptionRequest Request {
  host                 = "webdriver"
  port                 = 4444
  secure               = False
  requestHeaders       = [("Content-Type","application/json; charset=utf-8")]
  path                 = "/wd/hub/session"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (StatusCodeException (Response {responseStatus = Status {statusCode = 500, statusMessage = "Server Error"}, responseVersion = HTTP/1.1, responseHeaders = [("Content-Type","application/json;charset=utf-8"),("Content-Length","19447"),("Server","Jetty(9.4.z-SNAPSHOT)")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "{\n  \"value\": {\n    \"stacktrace\": \"org.openqa.selenium.WebDriverException: unknown error: cannot create default profile directory\\nBuild info: version: '3.141.59', 
```

"cannot create default profile directory" happens whether I specify the "profile-directory" or not and also whether or not user-data-dir already exists. It only happens if user-data-dir is specified. Any ideas what could be causing the issue? [I've temporarily removed all seemingly non-operative chrome flags in the above run to rule out contraindications].

**Comment by jleonard-r7** [comment]
Also, btw, `--no-sandbox-and-elevated` may be able to replace the combination of `--no-sandbox` and `--privileged` (I also tried with that to no avail). `--privileged` doesn't even seem to be a supported flag anymore (at least according to the documents I've searched).

**Review by owickstrom — CHANGES_REQUESTED** [review]
I'll only ask for `Text` to be used instead of `String`. Otherwise this looks great!

**Comment by owickstrom** [comment]
> Also, btw, `--no-sandbox-and-elevated` may be able to replace the combination of `--no-sandbox` and `--privileged` (I also tried with that to no avail). `--privileged` doesn't even seem to be a supported flag anymore (at least according to the documents I've searched).

Huh, I didn't know that. Do you have any link for reference docs?

**Comment by jleonard-r7** [comment]
https://peter.sh/experiments/chromium-command-line-switches/

(This seems like a non-Google source, but it is actually the one they point to from here:
https://www.chromium.org/developers/how-tos/run-chromium-with-flags)

**Comment by jleonard-r7** [comment]
Btw, why did you have no-sandbox as a flag initially anyway? Is it really required here? Seems like its use is discouraged as the selenium driver connects to the outside world and could "drive" the app under test in an insecure way.

If you really do want this however, it seems that '--no-sandbox-and-elevated' is the way to go nowadays. Would you like to include that change in this PR?

**Comment by jleonard-r7** [comment]
> I'll only ask for `Text` to be used instead of `String`. Otherwise this looks great!

Do you mind explaining why? I would lose the ability to use List.isPrefixOf and there's no "string builder" type of pattern here which would benefit from the performance improvements of Text. These are also very small one-of strings, which the consensus around seems to be that it is fine. However, from an "ideological purity" point of view, it makes sense. I'm sure there's equivalent "begins with" functions etc so no problem if this is your reasoning.

**Comment by owickstrom** [comment]
> > I'll only ask for `Text` to be used instead of `String`. Otherwise this looks great!
> 
> Do you mind explaining why? I would lose the ability to use List.isPrefixOf and there's no "string builder" type of pattern here which would benefit from the performance improvements of Text. These are also very small one-of strings, which the consensus around seems to be that it is fine. However, from an "ideological purity" point of view, it makes sense. I'm sure there's equivalent "begins with" functions etc so no problem if this is your reasoning.

It's because everything else in the code base uses (should, at least) Text. I'm not interested in debating "ideological purity". If you need to use string operations then you could convert back and forth with `toS`. But keep the type in data structures that are passed around as `Text`.

> If you really do want this however, it seems that '--no-sandbox-and-elevated' is the way to go nowadays. Would you like to include that change in this PR?

Sure. Or if you can remove it altogether, we could try that. I can't recall why it's there really.

**Comment by jleonard-r7** [comment]
To be clear, "ideological purity" is your position. Call it "consistency" if that suits you better. I have no problem with using the least powerful tool for any particular job (in fact I prefer it as a matter of principle). I will update per your request however so hopefully this can be merged.

**Review by owickstrom — APPROVED** [review]

**Pull request merged**
