### PR TITLE
Action seq reselect fix

### PR DESCRIPTION
**Pull request by owickstrom**

### CODE REVIEW

**Comment by owickstrom** [comment]
@jleonard-r7 I've added an integration test that I think resembles your use case.

**Comment by jleonard-r7** [comment]
I've verified that this branch does indeed fix our problem. However I had to add a new definition to quickstrom:

```
followedBySeq :: ProbabilisticAction -> ProbabilisticAction -> ProbabilisticAction
followedBySeq (ProbabilisticAction p0) (ProbabilisticAction p1) =
  ProbabilisticAction p1 { weighted = p0.weighted <> p1.weighted }
```

I will create a PR for this. Thanks!

**Comment by owickstrom** [comment]
Great!

**Comment by owickstrom** [comment]
@jleonard-r7 Instead of a new name `followedBySeq`, it could be an instance of `Semigroup` for `ProbabilisticAction`.

**Comment by jleonard-r7** [comment]
> @jleonard-r7 Instead of a new name `followedBySeq`, it could be an instance of `Semigroup` for `ProbabilisticAction`.

Okay 👌🏼

**Comment by owickstrom** [comment]
It's a bit scary that the weight is silently picked from the latter `ProbabilisticAction`. Maybe we can add a note in the docs about this, and suggest using `weighted` at the end of a chain.

**Comment by jleonard-r7** [comment]
It’s not scary to me. It’s exactly what I need/intend. One needs to pick one or the other and yes the idea is that you would specify the exact weight you want for the entire sequence in that position (whether it be the first or the last).

Certainly docs would be fine but isn’t this going to be moot if you are reworking this all to use preconditions?

**Comment by owickstrom** [comment]
OK. I can add the docs later. :+1:  They would eventually, but I'm not sure exactly when the new version is ready for use.

**Comment by jleonard-r7** [comment]
Actually I think I spoke too soon. I did see a successful run but now I am seeing a consistent failure:

```
Quickstrom Test Report
Failed with error: user error (Couldn't select a single element with selector: Selector "textarea")

user error (Couldn't select a single element with selector: Selector "textarea")
```

from the following code (the only instance of 'textarea' in my spec):

```
appFoci :: Actions
appFoci = [
  awaitWithTimeoutSecs 1 "#main-app" `followedBy` focus "input"
  , awaitWithTimeoutSecs 1 "#main-app" `followedBy` focus "textarea"  -- problem here, could be more than one text area or zero text areas ???
]

actions :: Actions
actions = [
  loginSeq1 `weighted` 2
  , loginSeq2 `weighted` 2
] <> appClicks <> appFoci

```

I'm not sure this bug is completely fixed. Seems like a very similar symptom to previously.

**Comment by owickstrom** [comment]
Do you get the same problem if you instead await `textarea` (rather than `#main-app`)?

**Comment by jleonard-r7** [comment]
Hmm, I'm not sure I can do that because only when #main-app is present are we inside the "app" we care about. Imagine a site that has a bunch of tiles each representing an "app". We only care about one of those apps. So, if quickstrom clicks into any of the others (or their text areas), it's completely wasted cycles. Since quickstrom is probabilistic, this greatly reduces the chances that we find any bugs in the actual app that we care about. That's why #main-app should be present _before_ we do any crawling in an area.

**Comment by owickstrom** [comment]
I see. But the textarea should be inside that `#main-app`? Then you could await `#main-app textarea`?

With the current behavior for action sequences, the selectors of subsequent actions are queried immediately and have to return at least one element. So, if you have the following sequence:

```
click "foo" `followedBy` click "bar"
```

And if the first action creates an element matching `"bar"` _after some time_, then the second action fails when querying `"bar"`. You'd need to do:

```
click "foo" `followedBy` await "bar" `followedBy` click "bar"
```

Not sure if you already had this mental model if the action sequences, just wanted to explain and make sure.

**Comment by jleonard-r7** [comment]
Ah, that makes sense. I think it's a bit of a departure from my original implementation which would just result in an abortion of the sequence if any step failed to select.

I think I like this better though. I will try to adjust my codes per this model. Thanks!

**Comment by owickstrom** [comment]
Cool! Let me know how it goes.

**Comment by jleonard-r7** [comment]
I got the same error with the following codes:

```
appFoci :: Actions
appFoci = [
  awaitWithTimeoutSecs 1 "#main-app input" `followedBy` focus "input"
  , awaitWithTimeoutSecs 1 "#main-app textarea" `followedBy` focus "textarea"
]
```

perhaps I need `awaitWithTimeoutSecs 1 ... `followedBy` await "textarea" `followedBy` focus "textarea"` ??

**Comment by jleonard-r7** [comment]
Oh, I think I remember the difference in behavior here:

My rendition of the code would consider a sequence with any selector failing to match as not eligible to be "selected" in the first place. Why is that not the case here? I would prefer that implementation and I am not seeing any easy way to make this one behave in the same manner. Does an `await` in the middle of a sequence allow for short-circuiting without blowing up the entire test run?

**Comment by jleonard-r7** [comment]
Does an `await` in the middle of a sequence like that abort the action without blowing up the entire test run?

**Comment by owickstrom** [comment]
Hmm, I think it does crash the entire test. I could change that, but I guess it wouldn't help you much. The idea is that if the first action in the sequence is enabled, then the rest of the sequence is expected to be enabled as it progresses.

Maybe your sequence is enabled (the first action) in situations where it should not be? It looks weird to have an `await`* at the beginning of the sequence, and possibly be that is causing your problem.

**Comment by jleonard-r7** [comment]
No, it isn’t weird at all as I have explained before. It was what I needed for my situation. 

Do you have any other suggestion (for my situation) since this apparently won’t work now that the code has been refactored to be wordier & allegedly easier to read (although now incorrect per my original design)?

**Comment by owickstrom** [comment]
We could change it so that it would be an action failure rather than a crash. I think that would make it equivalent to the original implementation you did?

**Comment by jleonard-r7** [comment]
Yes that’s right.

**Comment by owickstrom** [comment]
I'll put up a PR shortly.

**Comment by owickstrom** [comment]
#100 is ready if you want to test that.

**Pull request merged**
