### PR TITLE
Use ActionFailure instead of fail for selecting rest of seq

### PR DESCRIPTION
**Pull request by owickstrom**

### CODE REVIEW

**Review by jleonard-r7 — APPROVED** [review]

**Comment by jleonard-r7** [comment]
I'm getting a different error now:

```
Quickstrom Test Report
Failed with error: WebDriverOtherError "E (ResponseError ElementNotInteractable \"element not interactable\\n (Session info: headless chrome=85.0.4183.83)\" \"#0 0x55aeed744aa9 <unknown>\\n\" Nothing (Status {statusCode = 400, statusMessage = \"Bad Request\"}))"

WebDriverOtherError "E (ResponseError ElementNotInteractable \"element not interactable\\n (Session info: headless chrome=85.0.4183.83)\" \"#0 0x55aeed744aa9 <unknown>\\n\" Nothing (Status {statusCode = 400, statusMessage = \"Bad Request\"}))"
```

I've seen this error many times before but it's never blown up the tests completely. I think you've mentioned that you know the cause of it. Did the behavior somehow change on this one to now cause the tests to blow up completely (rather than continue on)?

**Comment by owickstrom** [comment]
That is weird. Looking into it and trying to replicate. Do you know if this happened during a "full" test or during a shrink?

**Comment by jleonard-r7** [comment]
There’s no mention of shrinking. Here’s the full cli output for the html run (and my previous paste was the html contents):

```
Version: 0.3.0
35

36
Running 5 tests...
37

38
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
39

40
20 actions
41
2021-04-23 17:21:45 ERROR  Error Response: 400 Bad Request
42
{
43
    "data": null,
44
    "error": 400,
45
    "stacktrace": "#0 0x55aeed744aa9 <unknown>\n",
46
    "message": "element not interactable\n  (Session info: headless chrome=85.0.4183.83)"
47
}
48

49
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
50

51
Error: Process completed with exit code 1.
```

**Comment by owickstrom** [comment]
This might be two problems at once:

* Some action not being sufficiently validated before picked (causing the "element not interactable" error)
* Quickstrom crashing because of this error, not just storing an action failure in the trace

Can you try removing actions from your spec to find out what action (sequence) causes this?

**Pull request merged**
