### PR TITLE
New API for actions in DSL

### PR DESCRIPTION
**Pull request by owickstrom**
This provides a new syntax for actions in specs. See https://quickstrom--89.org.readthedocs.build/en/89/topics/specification-language.html#actions for the new docs.

@johanatan This is likely affecting your specs, right? I've released a version 0.2.0 before this PR if you want to stick with that for now. But the changes required for the new syntax shouldn't be too big.

### CODE REVIEW

**Comment by johanatan** [comment]
Very nice! Yep, should be an easy update. 👍🏼

**Comment by jleonard-r7** [comment]
Has the behavior changed? I'm getting the following error which prevents tests from running after updating my action syntax (but no other change to the structure or logic of my spec):

```
Check encountered an error: user error (Cannot find elements to select for all subsequent actions in sequence: [Click (Selector "button")])
```

**Comment by jleonard-r7** [comment]
Note that this is with my `followedBySeq` addition to the DSL:

```
followedBySeq :: ProbabilisticAction -> ProbabilisticAction -> ProbabilisticAction
followedBySeq (ProbabilisticAction p0) (ProbabilisticAction p1) =
  ProbabilisticAction p1 { weighted = p0.weighted <> p1.weighted }
```

(which is required for subsequence re-use). i.e.,

https://github.com/jleonard-r7/quickstrom/commit/383b9cbd0f639f1b9aef76fc75bfd7887a5fd074

**Comment by jleonard-r7** [comment]
Looks like this is a breaking change for me:
https://github.com/quickstrom/quickstrom/blob/1615b6a3068eb4e915b0d4a0e6f559263b95d08f/runner/src/Quickstrom/Run/Actions.hs#L78

My specs were designed to operate with the previous behavior.  How do you suggest I redesign them?

**Comment by jleonard-r7** [comment]
For reference, here is the relevant bits (updated to the new syntax):

```
usernameEntry :: ProbabilisticAction
usernameEntry =
  focus "#okta-signin-username" `followedBy` enterText "username@somewhere.com"

passwordEntry :: ProbabilisticAction
passwordEntry =
  focus "input#okta-signin-password" `followedBy` enterText "thepassword"

loginSubmit :: ProbabilisticAction
loginSubmit =
  click "input#okta-signin-submit"
    `followedBy` await "h2.page-title"
    `followedBy` navigate "https://subdomain.domain.com/"
    `followedBy` await "#main-app"

loginSeq1 :: ProbabilisticAction
loginSeq1 = usernameEntry `followedBySeq` passwordEntry `followedBySeq` loginSubmit

loginSeq2 :: ProbabilisticAction
loginSeq2 = passwordEntry `followedBySeq`  usernameEntry `followedBySeq`  loginSubmit

appClicks :: Actions
appClicks = [
  awaitWithTimeoutSecs 1 "#main-app" `followedBy` click "button"   -- error seems to occur here; i.e., main-app present but buttons are not.
  , awaitWithTimeoutSecs 1 "#main-app" `followedBy` click "input[type=submit]"
  , awaitWithTimeoutSecs 1 "#main-app" `followedBy` click "a"
  , awaitWithTimeoutSecs 1 "div.app-card" `followedBy` click "div.app-card"
]

appFoci :: Actions
appFoci = [
  awaitWithTimeoutSecs 1 "#main-app" `followedBy` focus "input"
  , awaitWithTimeoutSecs 1 "#main-app" `followedBy` focus "textarea"
]

actions :: Actions
actions = [
  loginSeq1 `weighted` 2
  , loginSeq2 `weighted` 2
] <> appClicks <> appFoci

proposition :: Boolean
proposition =
  let
    initial = isJust loginTitle
    login = initial && next usingApp
    usingApp = not $ String.null $ fromMaybe "" appContent
    errorFree = Array.null allErrors
    logout = usingApp && next login
  in initial && always ( login || usingApp || logout ) && always errorFree
```

**Comment by jleonard-r7** [comment]
To elaborate: the previous behavior was for the action sequence to be considered ineligible for selection if either of the following were true: a) the conversion from `Selector` -> `Selected` for `head` of the sequence fails --or-- b) all of the `tail` selectors have the nil list as potential conversions (i.e., a priori to an actual conversion/selection taking place for them). It seems that now when b) is the case, your entire test is aborted with the error message I linked to and pasted above. My whole test design is predicated on the prior behavior and it isn't clear to me how (or even why) I would need to update my tests to faciliate the new behavior.

**Comment by owickstrom** [comment]
Thanks for reporting! Might very well be a regression/changed behavior. I have limited time this weekend to look into details, but I'll try to get it to it ASAP.

**Pull request merged**
